service: sls-py-sample

provider:
  name: aws
  runtime: python3.6
  memorySize: 128

package:
  exclude:
    - test.py

custom:
  pythonRequirements:
    dockerizePip: true
    dockerInDockerPath: /Users/farley/Projects/serverless-python-sample
    useDownloadCache: false
    useStaticCache: false


functions:
  listPosts:
    handler: handler.list_posts
    events:
      - http:
          path: posts
          method: get

  getPost:
    handler: handler.get_post
    events:
      - http:
          path: posts/{id}
          method: get

plugins:
  - serverless-python-requirements
