service: sls-py-sample

provider:
  name: aws
  runtime: python3.6
  memorySize: 128

custom:
  pythonRequirements:
    dockerizePip: true
    # dockerInDockerPath: /var/lib/docker/overlay2/28563d53cb02700ba5e0b6f60efa337fa9ba1e0cc38374967927a568c7df415e/merged/test
    useDownloadCache: false
    useStaticCache: false


functions:
  listPosts:
    handler: handler.list_posts
    events:
      - http:
          path: posts
          method: get

  getPost:
    handler: handler.get_post
    events:
      - http:
          path: posts/{id}
          method: get

plugins:
  - serverless-python-requirements


package:
  exclude:
    - "serverless.yml"
    - ".DS_Store"
    - ".git"
    - ".gitignore"
    - ".requirements"
    - ".serverless-python-requirements-static-cache"
    - "node_modules/**"
    - ".requirements/**"
    - "**.md"
    - "**tar.gz"
    - "**.sh"
    - "**.txt"
    - "**/**.yml"
    - "**.zip"
    - "package.json"
    - "package-lock.json"
    - "docs/**"
    - "tests/**"
    - "**.sql"